POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "active": 1,
    "email": "sidikinabe40@gmail.com",
    "password": "WUKAf35xfyul@",
    "firstName": "nabe",
    "lastName": "abou",
    "birthDate": "25/02/2002",
    "status": "ADMIN"

}

###
POST http://localhost:3000/me HTTP/1.1
Content-Type: application/json

{
    "email": "sidikinabe40@gmail.com",
    "password": "WUKAf35xfyul@"
}

###

POST http://localhost:3000/eleves HTTP/1.1
Content-Type: application/json
Authorization: LTAQXmtkPIiyRzNbFAedHBcdU

{
    "firstName": "abou",
    "lastName": "nabe",
    "filiere": "TECH",
    "classe": 2
}

###

GET http://localhost:3000/eleves/1 HTTP/1.1
Content-Type: application/json
Authorization: LTAQXmtkPIiyRzNbFAedHBcdU


###

PUT http://localhost:3000/eleves/1 HTTP/1.1
Content-Type: application/json
Authorization: LTAQXmtkPIiyRzNbFAedHBcdU

{
    "lastName":"Nabe"
}

###
DELETE http://localhost:3000/eleves/1 HTTP/1.1
Content-Type: application/json
Authorization: LTAQXmtkPIiyRzNbFAedHBcdU


###
POST http://localhost:3000/notes HTTP/1.1
Content-Type: application/json
Authorization: LTAQXmtkPIiyRzNbFAedHBcdU

{
    "eleveid": 1,
    "matiere": "ANGLAIS",
    "note": 10
}
