POST https://abouweb.alwaysdata.net/users HTTP/1.1
Content-Type: application/json

{
    "active": 1,
    "email": "sidikinabe10@gmail.com",
    "password": "WUKAf35xfyul@",
    "firstName": "nabe",
    "lastName": "abou",
    "birthDate": "25/02/2002",
    "status": "ADMIN"

}

###
POST https://abouweb.alwaysdata.net/me
Content-Type: application/json

{
    "email": "sidikinabe10@gmail.com",
    "password": "WUKAf35xfyul@"
}

###

POST https://abouweb.alwaysdata.net/eleves HTTP/1.1
Content-Type: application/json
Authorization: Bearer ZVJzEVftDGLnzIRvybprNmoxK

{
    "firstName": "aboubacar",
    "lastName": "nabee",
    "filiere": "TECH",
    "classe": 2
}

###

GET https://abouweb.alwaysdata.net/eleves/TECH HTTP/1.1
Content-Type: application/json
Authorization: Bearer ZVJzEVftDGLnzIRvybprNmoxk


###

PUT https://abouweb.alwaysdata.net/eleves/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer ZVJzEVftDGLnzIRvybprNmoxK

{
    "lastName":"nabeee"
}

###
DELETE https://abouweb.alwaysdata.net/eleves/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer ZVJzEVftDGLnzIRvybprNmoxK


###
POST https://abouweb.alwaysdata.net/notes HTTP/1.1
Content-Type: application/json
Authorization: Bearer ZVJzEVftDGLnzIRvybprNmoxK

{
    "eleveId": 2,
    "matiere": "MATH",
    "note": 15
}

###
GET https://abouweb.alwaysdata.net/notes/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer ZVJzEVftDGLnzIRvybprNmoxK

###
PUT https://abouweb.alwaysdata.net/notes/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer ZVJzEVftDGLnzIRvybprNmoxK


{
    "note":15
}

###
PUT https://abouweb.alwaysdata.net/disconnect HTTP/1.1
Content-Type: application/json
Authorization: Bearer ZVJzEVftDGLnzIRvybprNmoxK